const TunnelEvent = {
  SYNC_QUIZ_USER_REQ: 'XMZYE_SYNC_QUIZ_USER_REQ',
  SYNC_QUIZ_USER_RES: 'XMZYE_SYNC_QUIZ_USER_RES',
  REF_QUIZ_USER_REQ: 'XMZYE_REF_QUIZ_USER_REQ',
  REF_QUIZ_USER_RES: 'XMZYE_REF_QUIZ_USER_RES'
}

module.exports = TunnelEvent